spring.application.name=boot-data-app

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=tiger
spring.datasource.url=jdbc:mysql://localhost:3306/employee
spring.jpa.hibernate.ddl-auto=update

#displaying the table made by the framework
spring.jpa.show-sql=true